# Generated by Django 4.2.7 on 2025-10-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('clinic', 'Clinic'), ('hospital', 'Hospital')], default='hospital', max_length=20)),
                ('tagline', models.CharField(blank=True, help_text='Brief tagline or slogan', max_length=300, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('alternate_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hospital/')),
                ('working_hours', models.CharField(default='24/7', help_text="e.g., '9 AM - 9 PM' or '24/7'", max_length=100)),
                ('has_emergency', models.BooleanField(default=True, help_text='Has emergency services')),
                ('has_pharmacy', models.BooleanField(default=True, help_text='Has in-house pharmacy')),
                ('has_laboratory', models.BooleanField(default=True, help_text='Has in-house laboratory')),
                ('registration_number', models.CharField(blank=True, help_text='Hospital registration number', max_length=100, null=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hospital Configuration',
                'verbose_name_plural': 'Hospital Configuration',
                'db_table': 'hospital_config',
            },
        ),
    ]
