# Generated by Django 4.2.7 on 2025-10-19 20:05

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('diagnostic', 'Diagnostic'), ('nursing', 'Nursing Care'), ('home_care', 'Home Healthcare'), ('other', 'Other')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='service_categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'db_table': 'service_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NursingCarePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package_type', models.CharField(choices=[('hourly', 'Hourly'), ('half_day', 'Half Day'), ('full_day', 'Full Day')], max_length=20)),
                ('included_services', models.JSONField(blank=True, help_text='JSON list of included services', null=True)),
                ('max_duration', models.PositiveIntegerField(help_text='Maximum duration in hours')),
                ('target_group', models.CharField(choices=[('elderly', 'Elderly'), ('post_surgery', 'Post Surgery'), ('child_care', 'Child Care'), ('other', 'Other')], default='other', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_services', to='services.servicecategory')),
            ],
            options={
                'verbose_name_plural': 'Nursing Care Packages',
                'db_table': 'nursing_care_packages',
            },
        ),
        migrations.CreateModel(
            name='HomeHealthcareService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.CharField(choices=[('medical_assistance', 'Medical Assistance'), ('personal_care', 'Personal Care'), ('wound_care', 'Wound Care'), ('medication_management', 'Medication Management'), ('other', 'Other')], max_length=50)),
                ('staff_type_required', models.CharField(choices=[('nurse', 'Nurse'), ('caregiver', 'Caregiver'), ('physiotherapist', 'Physiotherapist'), ('doctor', 'Doctor')], max_length=50)),
                ('equipment_needed', models.TextField(blank=True, null=True)),
                ('max_distance_km', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_services', to='services.servicecategory')),
            ],
            options={
                'verbose_name_plural': 'Home Healthcare Services',
                'db_table': 'home_healthcare_services',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sample_type', models.CharField(choices=[('blood', 'Blood'), ('urine', 'Urine'), ('imaging', 'Imaging'), ('other', 'Other')], max_length=20)),
                ('is_home_collection', models.BooleanField(default=False)),
                ('home_collection_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('preparation_instructions', models.TextField(blank=True, null=True)),
                ('typical_turnaround_time', models.PositiveIntegerField(help_text='Turnaround time in hours')),
                ('reporting_type', models.CharField(choices=[('digital', 'Digital'), ('physical', 'Physical'), ('both', 'Both')], default='digital', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_services', to='services.servicecategory')),
            ],
            options={
                'verbose_name_plural': 'Diagnostic Tests',
                'db_table': 'diagnostic_tests',
            },
        ),
    ]
