# Generated by Django 5.2.7 on 2025-11-05 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opd", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalNoteTemplate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Template name (e.g., Initial Consultation Form)",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique template code", max_length=50, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Clinical Note Template",
                "verbose_name_plural": "Clinical Note Templates",
                "db_table": "clinical_note_templates",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ClinicalNoteTemplateGroup",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Group name (e.g., General Examination)",
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Order in which to display this group"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Clinical Note Template Group",
                "verbose_name_plural": "Clinical Note Template Groups",
                "db_table": "clinical_note_template_groups",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ClinicalNoteTemplateField",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "field_name",
                    models.CharField(
                        help_text="Internal field name (use lowercase, no spaces)",
                        max_length=100,
                    ),
                ),
                (
                    "field_label",
                    models.CharField(
                        help_text="Display label for the field", max_length=200
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text (Short)"),
                            ("textarea", "Text Area (Long)"),
                            ("number", "Number"),
                            ("decimal", "Decimal"),
                            ("boolean", "Boolean (Yes/No)"),
                            ("date", "Date"),
                            ("datetime", "Date & Time"),
                            ("time", "Time"),
                            ("select", "Single Select"),
                            ("multiselect", "Multiple Select"),
                            ("radio", "Radio Buttons"),
                            ("checkbox", "Checkboxes"),
                            ("image", "Image Upload"),
                            ("file", "File Upload"),
                            ("json", "JSON Data"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "help_text",
                    models.CharField(
                        blank=True,
                        help_text="Help text to display below the field",
                        max_length=500,
                    ),
                ),
                (
                    "placeholder",
                    models.CharField(
                        blank=True,
                        help_text="Placeholder text for input fields",
                        max_length=200,
                    ),
                ),
                (
                    "default_value",
                    models.TextField(
                        blank=True, help_text="Default value for the field"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False, help_text="Is this field mandatory?"
                    ),
                ),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum value (for number fields)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum value (for number fields)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "min_length",
                    models.IntegerField(
                        blank=True,
                        help_text="Minimum length (for text fields)",
                        null=True,
                    ),
                ),
                (
                    "max_length",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum length (for text fields)",
                        null=True,
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Order in which to display this field"
                    ),
                ),
                (
                    "column_width",
                    models.IntegerField(
                        choices=[
                            (1, "1/12"),
                            (2, "2/12"),
                            (3, "3/12"),
                            (4, "4/12"),
                            (5, "5/12"),
                            (6, "6/12"),
                            (7, "7/12"),
                            (8, "8/12"),
                            (9, "9/12"),
                            (10, "10/12"),
                            (11, "11/12"),
                            (12, "12/12"),
                        ],
                        default=12,
                        help_text="Bootstrap column width (1-12)",
                    ),
                ),
                (
                    "show_condition",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Conditions to show this field based on other fields",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="opd.clinicalnotetemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinical Note Template Field",
                "verbose_name_plural": "Clinical Note Template Fields",
                "db_table": "clinical_note_template_fields",
                "ordering": ["template", "display_order", "id"],
                "unique_together": {("template", "field_name")},
            },
        ),
        migrations.CreateModel(
            name="ClinicalNoteTemplateFieldOption",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "option_value",
                    models.CharField(help_text="Internal value", max_length=100),
                ),
                (
                    "option_label",
                    models.CharField(help_text="Display label", max_length=200),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data for the option",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="opd.clinicalnotetemplatefield",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Field Option",
                "verbose_name_plural": "Template Field Options",
                "db_table": "clinical_note_template_field_options",
                "ordering": ["field", "display_order", "option_label"],
                "unique_together": {("field", "option_value")},
            },
        ),
        migrations.AddField(
            model_name="clinicalnotetemplate",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="templates",
                to="opd.clinicalnotetemplategroup",
            ),
        ),
        migrations.CreateModel(
            name="ClinicalNoteTemplateResponse",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("response_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("completed", "Completed"),
                            ("reviewed", "Reviewed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "response_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Cached summary of all responses",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "filled_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filled_template_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_template_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="opd.clinicalnotetemplate",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_responses",
                        to="opd.visit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinical Note Template Response",
                "verbose_name_plural": "Clinical Note Template Responses",
                "db_table": "clinical_note_template_responses",
                "ordering": ["-response_date"],
                "unique_together": {("visit", "template")},
            },
        ),
        migrations.CreateModel(
            name="ClinicalNoteTemplateFieldResponse",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("value_text", models.TextField(blank=True)),
                (
                    "value_number",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("value_boolean", models.BooleanField(blank=True, null=True)),
                ("value_date", models.DateField(blank=True, null=True)),
                ("value_datetime", models.DateTimeField(blank=True, null=True)),
                ("value_time", models.TimeField(blank=True, null=True)),
                ("value_json", models.JSONField(blank=True, default=dict)),
                (
                    "value_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="clinical_notes/responses/%Y/%m/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="opd.clinicalnotetemplatefield",
                    ),
                ),
                (
                    "selected_options",
                    models.ManyToManyField(
                        blank=True,
                        related_name="field_responses",
                        to="opd.clinicalnotetemplatefieldoption",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_responses",
                        to="opd.clinicalnotetemplateresponse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Field Response",
                "verbose_name_plural": "Template Field Responses",
                "db_table": "clinical_note_template_field_responses",
                "ordering": ["response", "field__display_order"],
                "unique_together": {("response", "field")},
            },
        ),
    ]
