# Generated by Django 4.2.7 on 2025-10-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='follow_up_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Follow-up consultation fee in INR', max_digits=10),
        ),
    ]
