# Generated by Django 5.2.7 on 2025-10-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctoravailability",
            options={
                "ordering": ["doctor_id", "day_of_week", "start_time"],
                "verbose_name": "Doctor Availability",
                "verbose_name_plural": "Doctor Availability",
            },
        ),
        migrations.AlterModelOptions(
            name="doctorprofile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Doctor Profile",
                "verbose_name_plural": "Doctor Profiles",
            },
        ),
        migrations.AlterUniqueTogether(
            name="doctoravailability",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="doctoravailability",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("monday", "Monday"),
                    ("tuesday", "Tuesday"),
                    ("wednesday", "Wednesday"),
                    ("thursday", "Thursday"),
                    ("friday", "Friday"),
                    ("saturday", "Saturday"),
                    ("sunday", "Sunday"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="doctoravailability",
            name="max_appointments",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="consultation_duration",
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="is_available_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="languages_spoken",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="license_expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="license_issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="license_issuing_authority",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="medical_license_number",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="qualifications",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="signature",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("on_leave", "On Leave"),
                    ("inactive", "Inactive"),
                ],
                default="active",
                max_length=16,
            ),
        ),
    ]
