# Generated by Django 4.2.7 on 2025-10-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='check_in_time',
            field=models.DateTimeField(blank=True, help_text='Time when patient checked in for the appointment', null=True),
        ),
    ]
