# Generated by Django 4.2.7 on 2025-10-23 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0001_initial'),
        ('appointments', '0002_appointment_check_in_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='visit',
            field=models.ForeignKey(blank=True, help_text='Associated OPD visit when patient checks in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_appointment', to='opd.visit'),
        ),
    ]
